load(":toolchains.bzl", "osslsigncode_toolchain")

toolchain_type(
    name = "cosign_toolchain_type",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "osslsigncode_toolchain_type",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "openssl_toolchain_type",
    visibility = ["//visibility:public"],
)

osslsigncode_toolchain(
    name = "osslsigncode_toolchain_impl",
    osslsigncode = "@signing_osslsigncode//:osslsigncode_file",
)

toolchain(
    name = "registered_osslsigncode_toolchain",
    toolchain = ":osslsigncode_toolchain_impl",
    toolchain_type = ":osslsigncode_toolchain_type",
    visibility = ["//visibility:public"],
)
