"""Regenerates the checked-in development signing certificates.

Run with `bazel run //signing/tests/testdata_certs:regenerate`. The generated
material is committed to the repository so that the test suite itself needs no
network access, no host `openssl`, and no per-run key generation.

A single CA-issued certificate can serve all three signers, and the `shared`
set below is exactly that. The per-tool sets are kept alongside it because each
still needs its own coverage:

  shared   A CA-issued RSA code-signing certificate, plus the CA that issued
           it. osslsigncode and rcodesign consume it directly, and cosign
           imports the same key into its own envelope, so one credential backs
           every signer. Emitted as PEM and PKCS#12 so both the direct and the
           openssl-converted paths are covered.
  generic  A self-signed plain code-signing certificate built with
           `cryptography`. Apple's profile adds X.509 extensions that
           osslsigncode rejects as "unhandled critical extension", so this
           documents the certificate shape osslsigncode accepts on its own.
  apple    An Apple-profile certificate produced by rcodesign itself, which
           guarantees the result is something rcodesign can parse and that it
           carries the code-signing extensions Apple tooling expects. This is
           the set that cannot be shared.
  cosign   A native cosign key pair, covering the case where a project already
           has cosign keys and no conversion should happen.

The generic and apple sets are emitted as both PEM and PKCS#12 so that every
certificate form the `certificate` rule accepts is covered by a real
end-to-end signing test.
"""

import argparse
import base64
import datetime
import os
import pathlib
import shutil
import subprocess
import sys

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.serialization import pkcs12
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

# These certificates sign nothing but test fixtures, so the password is public
# by design. It is mirrored into certs.bzl for use from BUILD files.
PASSWORD = "rules-signing-dev"

# Fixtures are regenerated by hand, so a long life keeps the test suite from
# breaking on an arbitrary future date. The ceiling is 2049: X.509 UTCTime
# encodes a two-digit year, and rcodesign uses it unconditionally, so a
# notAfter past that point silently wraps into the past.
VALIDITY_DAYS = 365 * 20

COMMON_NAME = "rules_signing development (DO NOT TRUST)"
SHARED_ROOT_COMMON_NAME = "rules_signing development root CA (DO NOT TRUST)"
SHARED_CA_COMMON_NAME = "rules_signing development intermediate CA (DO NOT TRUST)"
SHARED_COMMON_NAME = "rules_signing development shared (DO NOT TRUST)"


def generate_generic(outdir: pathlib.Path) -> None:
    """Writes a plain code-signing certificate usable by osslsigncode."""

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, COMMON_NAME)])
    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=VALIDITY_DAYS))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=True,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(
            x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CODE_SIGNING]),
            critical=False,
        )
        .sign(key, hashes.SHA256())
    )

    key_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    cert_pem = cert.public_bytes(serialization.Encoding.PEM)

    # The unified PEM holds the key first so osslsigncode can be pointed at the
    # same file for both -certs and -key.
    (outdir / "generic.pem").write_bytes(key_pem + cert_pem)
    (outdir / "generic.crt").write_bytes(cert_pem)
    (outdir / "generic.p12").write_bytes(
        pkcs12.serialize_key_and_certificates(
            name=COMMON_NAME.encode("utf-8"),
            key=key,
            cert=cert,
            cas=None,
            encryption_algorithm=serialization.BestAvailableEncryption(
                PASSWORD.encode("utf-8")
            ),
        )
    )


def generate_shared(outdir: pathlib.Path) -> None:
    """Writes one CA-issued certificate that every signer can use.

    The three signers reject each other's credentials only because of what is
    *in* the certificate, not because of any real incompatibility: rcodesign's
    Apple profile carries critical extensions osslsigncode refuses, and cosign
    wants its own key envelope. A plain RSA code-signing certificate avoids the
    first problem, and cosign's `import-key-pair` rewraps the same key to solve
    the second, so this one credential backs all three.

    It is issued by a small CA rather than self-signed so that the `ca_file`
    attribute has a real chain to embed and verifiers have a root to anchor to.
    """

    now = datetime.datetime.now(datetime.timezone.utc)
    not_before = now - datetime.timedelta(days=1)
    not_after = now + datetime.timedelta(days=VALIDITY_DAYS)

    def issue(subject, issuer_name, issuer_key, key, ca, path_length=None):
        builder = (
            x509.CertificateBuilder()
            .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, subject)]))
            .issuer_name(issuer_name)
            .public_key(key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(not_before)
            .not_valid_after(not_after)
            .add_extension(
                x509.BasicConstraints(ca=ca, path_length=path_length), critical=True
            )
            .add_extension(
                x509.KeyUsage(
                    digital_signature=not ca,
                    content_commitment=not ca,
                    key_encipherment=False,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=ca,
                    crl_sign=ca,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
        )
        if not ca:
            builder = builder.add_extension(
                x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CODE_SIGNING]),
                critical=False,
            )
        return builder.sign(issuer_key, hashes.SHA256())

    def name_of(common_name):
        return x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common_name)])

    # Three levels on purpose. A verifier is given only the root, so the
    # intermediate has to travel inside the signature itself; if `ca_file` were
    # ignored, verification would fail for want of a path to the root. A
    # two-level chain could not show that, because the leaf is always embedded.
    root_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    root_cert = issue(
        SHARED_ROOT_COMMON_NAME, name_of(SHARED_ROOT_COMMON_NAME), root_key,
        root_key, ca=True, path_length=1,
    )

    intermediate_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    intermediate_cert = issue(
        SHARED_CA_COMMON_NAME, root_cert.subject, root_key,
        intermediate_key, ca=True, path_length=0,
    )

    leaf_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    leaf_cert = issue(
        SHARED_COMMON_NAME, intermediate_cert.subject, intermediate_key,
        leaf_key, ca=False,
    )

    root_pem = root_cert.public_bytes(serialization.Encoding.PEM)
    intermediate_pem = intermediate_cert.public_bytes(serialization.Encoding.PEM)
    leaf_pem = leaf_cert.public_bytes(serialization.Encoding.PEM)
    leaf_key_pem = leaf_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

    # The trust anchor a verifier is configured with.
    (outdir / "shared_root.crt").write_bytes(root_pem)
    # What `ca_file` points at: the part of the chain that must be embedded.
    (outdir / "shared_ca.crt").write_bytes(intermediate_pem)
    # Key first, so osslsigncode can use one file for both -certs and -key.
    (outdir / "shared.pem").write_bytes(leaf_key_pem + leaf_pem)
    (outdir / "shared.crt").write_bytes(leaf_pem)

    # cosign verifies against a bare public key rather than a certificate, so
    # the leaf's public half is written in the form `cosign verify-blob --key`
    # expects. It is the same key the certificate carries.
    (outdir / "shared.pub").write_bytes(
        leaf_key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
    )

    (outdir / "shared.p12").write_bytes(
        pkcs12.serialize_key_and_certificates(
            name=SHARED_COMMON_NAME.encode("utf-8"),
            key=leaf_key,
            cert=leaf_cert,
            cas=[intermediate_cert, root_cert],
            encryption_algorithm=serialization.BestAvailableEncryption(
                PASSWORD.encode("utf-8")
            ),
        )
    )


def generate_apple(outdir: pathlib.Path, rcodesign: str) -> None:
    """Writes an Apple-profile certificate using rcodesign's own generator."""

    subprocess.run(
        [
            rcodesign,
            "generate-self-signed-certificate",
            "--person-name",
            COMMON_NAME,
            "--validity-days",
            str(VALIDITY_DAYS),
            "--pem-unified-file",
            str(outdir / "apple.pem"),
            "--pem-filename",
            str(outdir / "apple"),
            "--p12-file",
            str(outdir / "apple.p12"),
            "--p12-password",
            PASSWORD,
        ],
        check=True,
    )
    # --pem-filename writes <base>.crt and <base>.key; the private half is
    # already in apple.pem, so only the public certificate is kept.
    (outdir / "apple.key").unlink(missing_ok=True)


def generate_cosign(outdir: pathlib.Path, cosign: str) -> None:
    """Writes a cosign key pair in cosign's own encrypted key format."""

    for stale in ("cosign.key", "cosign.pub"):
        (outdir / stale).unlink(missing_ok=True)

    env = os.environ.copy()
    env["COSIGN_PASSWORD"] = PASSWORD
    subprocess.run(
        [cosign, "generate-key-pair", "--output-key-prefix", str(outdir / "cosign")],
        check=True,
        env=env,
    )


def write_certs_bzl(outdir: pathlib.Path) -> None:
    """Emits Starlark constants for material that BUILD files need inline.

    `certificate.certificate` is a string attribute, so the base64 encoding
    mode cannot read a file; the encoded certificate has to be available at
    loading time.
    """

    encoded = base64.b64encode((outdir / "generic.p12").read_bytes()).decode("ascii")
    shared_encoded = base64.b64encode(
        (outdir / "shared.p12").read_bytes()
    ).decode("ascii")
    (outdir / "certs.bzl").write_text(
        '"""Generated by //signing/tests/testdata_certs:regenerate. Do not edit."""\n'
        "\n"
        "# Password protecting the checked-in development certificates. These sign\n"
        "# nothing but test fixtures, so it is deliberately public.\n"
        'DEV_CERT_PASSWORD = "{password}"\n'
        "\n"
        '# generic.p12 encoded for the `certificate_encoding = "base64"` mode,\n'
        "# which takes the certificate as a string rather than as a file.\n"
        'DEV_GENERIC_P12_BASE64 = "{encoded}"\n'
        "\n"
        "# The CA-issued certificate every signer shares, in the same base64\n"
        "# form. Exercises converting PKCS#12 material to the PEM cosign needs.\n"
        'DEV_SHARED_P12_BASE64 = "{shared_encoded}"\n'.format(
            password=PASSWORD,
            encoded=encoded,
            shared_encoded=shared_encoded,
        ),
        encoding="utf-8",
    )


def resolve_tool(explicit: str, name: str) -> str:
    tool = explicit or shutil.which(name)
    if not tool:
        sys.exit("{0} not found; pass --{0}=<path> or put it on PATH".format(name))
    return tool


def assert_not_expired(outdir: pathlib.Path) -> None:
    """Fails if a generated certificate is not actually valid into the future.

    rcodesign encodes notAfter as X.509 UTCTime, whose two-digit year cannot
    represent anything past 2049; asking for a longer validity silently wraps
    the expiry into the past instead of erroring. Checking here turns that into
    an immediate failure rather than a confusing signature error later.
    """

    now = datetime.datetime.now(datetime.timezone.utc)
    for name in ("generic.crt", "shared_root.crt", "shared_ca.crt", "shared.crt", "apple.crt"):
        cert = x509.load_pem_x509_certificate((outdir / name).read_bytes())
        # not_valid_after_utc replaced the naive not_valid_after in
        # cryptography 42; accept either so the script is not pinned to one.
        not_after = getattr(cert, "not_valid_after_utc", None)
        if not_after is None:
            not_after = cert.not_valid_after.replace(tzinfo=datetime.timezone.utc)
        if not_after <= now:
            sys.exit(
                "{} expires at {}, which is not in the future; lower "
                "VALIDITY_DAYS".format(name, not_after)
            )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--outdir",
        default="",
        help="Where to write the fixtures. Defaults to this package's source directory.",
    )
    parser.add_argument("--rcodesign", default="", help="Path to the rcodesign binary.")
    parser.add_argument("--cosign", default="", help="Path to the cosign binary.")
    args = parser.parse_args()

    outdir = pathlib.Path(
        args.outdir
        or os.path.join(
            os.environ.get("BUILD_WORKSPACE_DIRECTORY", "."),
            "signing/tests/testdata_certs",
        )
    )
    outdir.mkdir(parents=True, exist_ok=True)

    generate_generic(outdir)
    generate_shared(outdir)
    generate_apple(outdir, resolve_tool(args.rcodesign, "rcodesign"))
    generate_cosign(outdir, resolve_tool(args.cosign, "cosign"))
    assert_not_expired(outdir)
    write_certs_bzl(outdir)
    print("wrote development certificates to {}".format(outdir))


if __name__ == "__main__":
    main()
